### ISSUE TITLE
开发手册插图外链URL失效

### ISSUE THREAD

**Issue by liuqun** [Lichee-Pi/Tang_Doc_Backup#3]
建议: 将外链插图导入git仓库, 与rst文档存放在同一个文件夹下

失效的插图为
- http://odfef978i.bkt.clouddn.com/E203_TD_download.png
- http://odfef978i.bkt.clouddn.com/E203_TD_add.png

如图
![image](https://user-images.githubusercontent.com/64795/49784280-b6767a00-fd57-11e8-81d5-3b9aafb51c0d.png)

http://tang.lichee.pro/get_started/fpga_download.html

https://github.com/Lichee-Pi/Tang_Doc_Backup/blob/3e8e84fccc6fbe3ef2b8b7262afba0894847f985/get_started/fpga_download.rst#L7-L15

**Comment by xelll** [comment]
谢谢您的反馈，已经修复了






在 2018-12-11 15:16:28，"刘群" <notifications@github.com> 写道：


建议: 将外链插图导入git仓库, 与rst文档存放在同一个文件夹下

失效的插图为

http://odfef978i.bkt.clouddn.com/E203_TD_download.png
http://odfef978i.bkt.clouddn.com/E203_TD_add.png

如图


http://tang.lichee.pro/get_started/fpga_download.html

https://github.com/Lichee-Pi/Tang_Doc_Backup/blob/3e8e84fccc6fbe3ef2b8b7262afba0894847f985/get_started/fpga_download.rst#L7-L15

**Comment by liuqun** [comment]
fixed by 978ecda
